### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by yizreel-Chen** [Kosteron/Conky#2]
I followed the installtion steps but when I tried to execute the "conky-launch.sh" by `./conky-launch.sh`, it shows:
```
sh: line 1: xdpyinfo: command not found
sh: line 1: ncal: command not found

```
and Showing this untill I kill the terminal, where is wrong?

**Comment by Kosteron** [comment]
Hello,

Which Linux distribution do you use? 
ncal is provided by the package **ncal**. and xdpyinfo is provided by **x11-utils** on a Ubuntu distro
but if you don't have x11-utils maybe you have something else.

I hope this information will be useful to you
